# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\x12\x0bhealthCheck\"\x14\n\x04Ping\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x14\n\x04Pong\x12\x0c\n\x04text\x18\x01 \x01(\t2\xe9\x01\n\x0bHealthCheck\x12\x32\n\x08PingPong\x12\x11.healthCheck.Ping\x1a\x11.healthCheck.Pong\"\x00\x12\x35\n\tPingsPong\x12\x11.healthCheck.Ping\x1a\x11.healthCheck.Pong\"\x00(\x01\x12\x35\n\tPingPongs\x12\x11.healthCheck.Ping\x1a\x11.healthCheck.Pong\"\x00\x30\x01\x12\x38\n\nPingsPongs\x12\x11.healthCheck.Ping\x1a\x11.healthCheck.Pong\"\x00(\x01\x30\x01\x62\x06proto3')



_PING = DESCRIPTOR.message_types_by_name['Ping']
_PONG = DESCRIPTOR.message_types_by_name['Pong']
Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'ping_pb2'
  # @@protoc_insertion_point(class_scope:healthCheck.Ping)
  })
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'ping_pb2'
  # @@protoc_insertion_point(class_scope:healthCheck.Pong)
  })
_sym_db.RegisterMessage(Pong)

_HEALTHCHECK = DESCRIPTOR.services_by_name['HealthCheck']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PING._serialized_start=27
  _PING._serialized_end=47
  _PONG._serialized_start=49
  _PONG._serialized_end=69
  _HEALTHCHECK._serialized_start=72
  _HEALTHCHECK._serialized_end=305
# @@protoc_insertion_point(module_scope)
