# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ping_pb2 as ping__pb2


class HealthCheckStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingPong = channel.unary_unary(
                '/healthCheck.HealthCheck/PingPong',
                request_serializer=ping__pb2.Ping.SerializeToString,
                response_deserializer=ping__pb2.Pong.FromString,
                )
        self.PingsPong = channel.stream_unary(
                '/healthCheck.HealthCheck/PingsPong',
                request_serializer=ping__pb2.Ping.SerializeToString,
                response_deserializer=ping__pb2.Pong.FromString,
                )
        self.PingPongs = channel.unary_stream(
                '/healthCheck.HealthCheck/PingPongs',
                request_serializer=ping__pb2.Ping.SerializeToString,
                response_deserializer=ping__pb2.Pong.FromString,
                )
        self.PingsPongs = channel.stream_stream(
                '/healthCheck.HealthCheck/PingsPongs',
                request_serializer=ping__pb2.Ping.SerializeToString,
                response_deserializer=ping__pb2.Pong.FromString,
                )


class HealthCheckServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingPong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingsPong(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingPongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingsPongs(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingPong': grpc.unary_unary_rpc_method_handler(
                    servicer.PingPong,
                    request_deserializer=ping__pb2.Ping.FromString,
                    response_serializer=ping__pb2.Pong.SerializeToString,
            ),
            'PingsPong': grpc.stream_unary_rpc_method_handler(
                    servicer.PingsPong,
                    request_deserializer=ping__pb2.Ping.FromString,
                    response_serializer=ping__pb2.Pong.SerializeToString,
            ),
            'PingPongs': grpc.unary_stream_rpc_method_handler(
                    servicer.PingPongs,
                    request_deserializer=ping__pb2.Ping.FromString,
                    response_serializer=ping__pb2.Pong.SerializeToString,
            ),
            'PingsPongs': grpc.stream_stream_rpc_method_handler(
                    servicer.PingsPongs,
                    request_deserializer=ping__pb2.Ping.FromString,
                    response_serializer=ping__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'healthCheck.HealthCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HealthCheck(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingPong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/healthCheck.HealthCheck/PingPong',
            ping__pb2.Ping.SerializeToString,
            ping__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PingsPong(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/healthCheck.HealthCheck/PingsPong',
            ping__pb2.Ping.SerializeToString,
            ping__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PingPongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/healthCheck.HealthCheck/PingPongs',
            ping__pb2.Ping.SerializeToString,
            ping__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PingsPongs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/healthCheck.HealthCheck/PingsPongs',
            ping__pb2.Ping.SerializeToString,
            ping__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
